apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodechat-deployment
  labels:
    app: my-node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-node-app
  template:
    metadata:
      labels:
        app: my-node-app
    spec:
      containers:
      - name: nodechat
        imagePullPolicy: Always
        image: srijaldocker/nodechat:latest
        ports:
        - containerPort: 3000
