name: Deploy to k3d

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List files
      run: ls -al

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}


    - name: Debug base64 kubeconfig
      env:
        KUBECONFIG_BASE64: ${{ secrets.KUBECONFIG_BASE64 }}
      run: |
        echo "$KUBECONFIG_BASE64"


    - name: Build and push Docker image
      run: |
        COMMIT_ID=${{ github.sha }}
        docker build -t srijaldocker/nodechat:${COMMIT_ID} .
        docker push ${{ secrets.DOCKER_USERNAME }}/nodechat:${COMMIT_ID}

    - name: Set up kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
        sudo apt-get update
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

    - name: Decode and configure kubeconfig
      env:
        KUBECONFIG_BASE64: ${{ secrets.KUBECONFIG_BASE64 }}
      run: |
        mkdir -p $HOME/.kube
        echo "${KUBECONFIG_BASE64}" | base64 --decode > $HOME/.kube/config

    - name: Check Kubernetes cluster info
      run: |
        cat $HOME/.kube/config
        export KUBECONFIG=$HOME/.kube/config
        chmod 600 ~/.kube/config
        kubectl cluster-info
   
    - name: Deploy to Kubernetes
      run: |
        export KUBECONFIG=$HOME/.kube/config
        kubectl apply -f deployment.yaml --validate=false
        kubectl apply -f service.yaml --validate=false
